package br.com.projeto.view;

import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LucasVerly
 */
public class MenuPrincipal extends javax.swing.JFrame {
    //public String usuarioLogado;
    /**
     * Creates new form barbearia
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userLogado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuClientes = new javax.swing.JMenu();
        menuCadastroCliente = new javax.swing.JMenuItem();
        menuControleCliente = new javax.swing.JMenuItem();
        menuFuncionarios = new javax.swing.JMenu();
        menuCadastroFuncionario = new javax.swing.JMenuItem();
        menuControleFuncionario = new javax.swing.JMenuItem();
        menuFornecedores = new javax.swing.JMenu();
        menuCadastroFornecedores = new javax.swing.JMenuItem();
        menuControleFornecedores = new javax.swing.JMenuItem();
        menuProdutos = new javax.swing.JMenu();
        menuCadastroProduto = new javax.swing.JMenuItem();
        menuControleProdutos = new javax.swing.JMenuItem();
        menuVendas = new javax.swing.JMenu();
        menuAbrirVenda = new javax.swing.JMenuItem();
        menuControleVenda = new javax.swing.JMenuItem();
        menuHistoricoVenda = new javax.swing.JMenuItem();
        menuConfiguracoes = new javax.swing.JMenu();
        menuTrocaUsuario = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Usuário Logado :");

        userLogado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        userLogado.setForeground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1345, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userLogado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 920, 1920, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projeto/imagens/fundomercado.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 920));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        menuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projeto/imagens/icons/clientes.png"))); // NOI18N
        menuClientes.setText("Clientes");

        menuCadastroCliente.setText("Cadastro de Clientes");
        menuCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroClienteActionPerformed(evt);
            }
        });
        menuClientes.add(menuCadastroCliente);

        menuControleCliente.setText("Controle de Clientes");
        menuControleCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuControleClienteActionPerformed(evt);
            }
        });
        menuClientes.add(menuControleCliente);

        jMenuBar1.add(menuClientes);

        menuFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projeto/imagens/icons/funcionarios.png"))); // NOI18N
        menuFuncionarios.setText("Funcionários");

        menuCadastroFuncionario.setText("Cadastro de Funcionários");
        menuCadastroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroFuncionarioActionPerformed(evt);
            }
        });
        menuFuncionarios.add(menuCadastroFuncionario);

        menuControleFuncionario.setText("Controle de Funcionários");
        menuControleFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuControleFuncionarioActionPerformed(evt);
            }
        });
        menuFuncionarios.add(menuControleFuncionario);

        jMenuBar1.add(menuFuncionarios);

        menuFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projeto/imagens/icons/fornecedores.png"))); // NOI18N
        menuFornecedores.setText("Fornecedores");

        menuCadastroFornecedores.setText("Cadastro de Fornecedores");
        menuCadastroFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroFornecedoresActionPerformed(evt);
            }
        });
        menuFornecedores.add(menuCadastroFornecedores);

        menuControleFornecedores.setText("Controle de Fornecedores");
        menuControleFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuControleFornecedoresActionPerformed(evt);
            }
        });
        menuFornecedores.add(menuControleFornecedores);

        jMenuBar1.add(menuFornecedores);

        menuProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projeto/imagens/icons/produtos.png"))); // NOI18N
        menuProdutos.setText("Produtos");

        menuCadastroProduto.setText("Cadastro de Produtos");
        menuCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroProdutoActionPerformed(evt);
            }
        });
        menuProdutos.add(menuCadastroProduto);

        menuControleProdutos.setText("Controle de Produtos");
        menuControleProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuControleProdutosActionPerformed(evt);
            }
        });
        menuProdutos.add(menuControleProdutos);

        jMenuBar1.add(menuProdutos);

        menuVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projeto/imagens/icons/vendas.png"))); // NOI18N
        menuVendas.setText("Vendas");

        menuAbrirVenda.setText("Abrir Venda");
        menuAbrirVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbrirVendaActionPerformed(evt);
            }
        });
        menuVendas.add(menuAbrirVenda);

        menuControleVenda.setText("Controle de Vendas");
        menuVendas.add(menuControleVenda);

        menuHistoricoVenda.setText("Histórico de Venda");
        menuHistoricoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHistoricoVendaActionPerformed(evt);
            }
        });
        menuVendas.add(menuHistoricoVenda);

        jMenuBar1.add(menuVendas);

        menuConfiguracoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projeto/imagens/icons/configuracoes.png"))); // NOI18N
        menuConfiguracoes.setText("Configurações");

        menuTrocaUsuario.setText("Trocar Usuário");
        menuTrocaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTrocaUsuarioActionPerformed(evt);
            }
        });
        menuConfiguracoes.add(menuTrocaUsuario);

        jMenuBar1.add(menuConfiguracoes);

        menuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projeto/imagens/icons/sair.png"))); // NOI18N
        menuSair.setText("Sair");
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        // TODO add your handling code here:
        int op;
        op = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?");
        
        if(op == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_menuSairMouseClicked

    private void menuCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroClienteActionPerformed
        // TODO add your handling code here:
        CadastroCliente cadastroCliente = new CadastroCliente ();
        cadastroCliente.setVisible(true);
    }//GEN-LAST:event_menuCadastroClienteActionPerformed

    private void menuTrocaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTrocaUsuarioActionPerformed
        // TODO add your handling code here:
        Login login = new Login ();
        this.dispose();
        login.setVisible(true);
    }//GEN-LAST:event_menuTrocaUsuarioActionPerformed

    private void menuCadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroFuncionarioActionPerformed
        // TODO add your handling code here:
        CadastroFuncionario cadastroFuncionario = new CadastroFuncionario();
        cadastroFuncionario.setVisible(true);
    }//GEN-LAST:event_menuCadastroFuncionarioActionPerformed

    private void menuControleClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuControleClienteActionPerformed
        // TODO add your handling code here:
        ControleCliente controleCliente = new ControleCliente();
        controleCliente.setVisible(true);
    }//GEN-LAST:event_menuControleClienteActionPerformed

    private void menuControleFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuControleFuncionarioActionPerformed
        // TODO add your handling code here:
        ControleFuncionario controleFuncionario = new ControleFuncionario();
        controleFuncionario.setVisible(true);
    }//GEN-LAST:event_menuControleFuncionarioActionPerformed

    private void menuControleFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuControleFornecedoresActionPerformed
        // TODO add your handling code here:
        ControleFornecedor controleFornecedor = new ControleFornecedor ();
        controleFornecedor.setVisible(true);
    }//GEN-LAST:event_menuControleFornecedoresActionPerformed

    private void menuCadastroFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroFornecedoresActionPerformed
        // TODO add your handling code here:
        CadastroFornecedor cadastroFornecedor = new CadastroFornecedor();
        cadastroFornecedor.setVisible(true);
    }//GEN-LAST:event_menuCadastroFornecedoresActionPerformed

    private void menuCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroProdutoActionPerformed
        // TODO add your handling code here:
        CadastroProduto cadastroProduto = new CadastroProduto ();
        cadastroProduto.setVisible(true);
    }//GEN-LAST:event_menuCadastroProdutoActionPerformed

    private void menuControleProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuControleProdutosActionPerformed
        // TODO add your handling code here:
        ControleProduto controleProduto = new ControleProduto ();
        controleProduto.setVisible(true);
    }//GEN-LAST:event_menuControleProdutosActionPerformed

    private void menuAbrirVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbrirVendaActionPerformed
        // TODO add your handling code here:
        PainelVenda painelVenda = new PainelVenda ();
        painelVenda.setVisible(true);
     
    }//GEN-LAST:event_menuAbrirVendaActionPerformed

    private void menuHistoricoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHistoricoVendaActionPerformed
        // TODO add your handling code here:
        HistoricoVenda historicoVenda = new HistoricoVenda ();
        historicoVenda.setVisible(true);
    }//GEN-LAST:event_menuHistoricoVendaActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        this.setExtendedState(this.MAXIMIZED_BOTH);
        //userLogado.setText(usuarioLogado);
        setVisible(true);
    }//GEN-LAST:event_formWindowActivated

    public void setUserLogado(String usuarioLogado) {
        userLogado.setText(usuarioLogado);
    }
    
    public void menuUsuario (boolean visible){
        menuFuncionarios.setEnabled(visible);
        menuFornecedores.setEnabled(visible);
        menuProdutos.setEnabled(visible);
        menuControleCliente.setEnabled(visible);
        menuControleVenda.setEnabled(visible);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuAbrirVenda;
    private javax.swing.JMenuItem menuCadastroCliente;
    private javax.swing.JMenuItem menuCadastroFornecedores;
    private javax.swing.JMenuItem menuCadastroFuncionario;
    private javax.swing.JMenuItem menuCadastroProduto;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenu menuConfiguracoes;
    private javax.swing.JMenuItem menuControleCliente;
    private javax.swing.JMenuItem menuControleFornecedores;
    private javax.swing.JMenuItem menuControleFuncionario;
    private javax.swing.JMenuItem menuControleProdutos;
    private javax.swing.JMenuItem menuControleVenda;
    private javax.swing.JMenu menuFornecedores;
    private javax.swing.JMenu menuFuncionarios;
    private javax.swing.JMenuItem menuHistoricoVenda;
    private javax.swing.JMenu menuProdutos;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenuItem menuTrocaUsuario;
    private javax.swing.JMenu menuVendas;
    private javax.swing.JLabel userLogado;
    // End of variables declaration//GEN-END:variables

}
